### ISSUE TITLE
New solution

### ISSUE THREAD

**Issue by Chinmay-Dorge** [jp9573/LeetCode-Solutions#1]
I would like to add solution for a LeetCode problem

**Comment by jp9573** [comment]
Hey Chinmay,

Good to know that, you can choose any problem from the LeetCode and create a PR.
If you are new, you can refer to the [steps here](https://github.com/jp9573/LeetCode-Solutions#leetcode-solutions). Please let me know if you need any help.

**Comment by jp9573** [comment]
> I have made my pull request

Great, I have reviewed it and merged it. :)
